# Generated by Django 6.0.4 on 2026-04-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان دسته بندی')),
                ('search_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='جستجو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge_tree.categorynode', verbose_name='سرخاشه (پدر)')),
            ],
            options={
                'verbose_name': 'درخت دانش',
                'verbose_name_plural': 'درخت دانش',
                'ordering': ('-created_at',),
            },
        ),
    ]
