# Generated by Django 6.0.4 on 2026-04-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynode',
            name='form_schema',
            field=models.JSONField(blank=True, help_text="تعریف فیلدهای فرم برای فرانت\u200cاند. مثال: [{'name': 'amount', 'type': 'number', 'required': True}]", null=True, verbose_name='فرم داینامیک درخت دانش'),
        ),
        migrations.AlterField(
            model_name='categorynode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge_tree.categorynode', verbose_name='سرخاشه (موضوع اصلی)'),
        ),
    ]
