# Generated by Django 6.0.4 on 2026-04-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0002_categorynode_form_schema_alter_categorynode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynode',
            name='guideline',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
