# Generated by Django 6.0.4 on 2026-05-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0003_categorynode_guideline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorynode',
            name='form_schema',
        ),
    ]
