# Generated by Django 6.0.4 on 2026-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0004_remove_categorynode_form_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynode',
            name='zammad_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
