# Generated by Django 6.0.4 on 2026-05-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0005_categorynode_zammad_group'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynode',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_nodes', to='workflow.workflow', verbose_name='گردشکار متصل'),
        ),
    ]
