# Generated by Django 6.0.4 on 2026-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0006_categorynode_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynode',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='تگ ها'),
        ),
    ]
