# Generated by Django 6.0.4 on 2026-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0007_categorynode_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorynode',
            name='tags',
        ),
        migrations.AddField(
            model_name='categorynode',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='nodes', to='knowledge_tree.tag', verbose_name='تگ ها'),
        ),
    ]
