# Generated by Django 6.0.4 on 2026-05-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام اکشن')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد سیستمی')),
                ('has_choices', models.BooleanField(default=False, verbose_name='آیا خروجی چندراهی دارد؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیخات اکشن')),
            ],
            options={
                'verbose_name': 'تعریف اکشن',
                'verbose_name_plural': 'تعریف اکشن ها',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گردشکار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گردشگار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گردشکار',
                'verbose_name_plural': 'گردشکارها',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مرحله')),
                ('is_start_node', models.BooleanField(default=False, verbose_name='آیا گره شروع است؟')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات JSON')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.actiondefinition', verbose_name='نوع اکشن')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'مرحله گردشکار',
                'verbose_name_plural': 'مراحل گردشکار',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرط عبور')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='workflow.workflow')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='workflow.workflowstep')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='workflow.workflowstep')),
            ],
            options={
                'verbose_name': 'مسیر گردش\u200cکار',
                'verbose_name_plural': 'مسیرهای گردش\u200cکار',
            },
        ),
    ]
