# Generated by Django 6.0.4 on 2026-05-23 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_ticketworkflowstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketworkflowstate',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_workflow_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
    ]
