# Generated by Django 6.0.4 on 2026-05-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_tree', '0003_categorynode_guideline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فرم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فرم')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن فرم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='برچسب فیلد')),
                ('field_type', models.CharField(choices=[('text', 'متن'), ('textarea', 'متن بلند'), ('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('bool', 'تاییده (checkbox)'), ('select', 'انتخابی (selectBox)'), ('date', 'تاریخ و زمان')], max_length=55, verbose_name='نوع فیلد')),
                ('required', models.BooleanField(default=False, verbose_name='فیلد اجباری است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_forms.dynamicform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zammad_ticket_id', models.IntegerField(db_index=True, verbose_name='آیدی تیکت در سیستم')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dynamic_forms.formfield')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال در این دسته')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش در این دسته')),
                ('category_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='knowledge_tree.categorynode')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.formfield')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category_node', 'field')},
            },
        ),
    ]
