# Generated by Django 6.0.4 on 2026-05-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfield',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='اجباری در این دسته'),
        ),
    ]
