# Generated by Django 6.0.4 on 2026-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_categoryfield_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='options',
            field=models.CharField(blank=True, max_length=1550, null=True, verbose_name='گزینه ها'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'متن'), ('textarea', 'متن بلند'), ('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('bool', 'تاییده (checkbox)'), ('select', 'انتخابی (selectBox)'), ('multiselect', 'چندانتخابی'), ('date', 'تاریخ و زمان')], max_length=55, verbose_name='نوع فیلد'),
        ),
    ]
